# Site settings
email: okay@samesies.io
baseurl: ""
paginate: 12
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
name: Thomas Vaeth
title: Barber
description: >
  Barber is a blog theme for Jekyll built by Thomas Vaeth for Samesies using HTML, Sass, and JavaScript.
url: "http://barber.samesies.io"
twitter_username: thomasvaeth
default_img: 

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - node_modules
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
