# Site settings
email: okay@samesies.io
baseurl: ""
paginate: 12
paginate_path: "/page/:num"
google_analytics: 

# SEO settings
name: Thomas Vaeth
title: The Barber Theme
description: >
  Barber is a blog theme for Jekyll built by Thomas Vaeth for Samesies using HTML, Sass, and JavaScript.
url: "http://barber.samesies.io"
twitter_username: thomasvaeth
default_img: /assets/images/seo.jpg
social:
  twitter: https://twitter.com/thomasvaeth
  instagram: https://www.instagram.com/thomas.vaeth/
  linkedin: https://www.linkedin.com/in/thomasvaeth/
  github: https://github.com/samesies
  codepen: https://codepen.io/thomasvaeth/

# Author settings
author:
  Thomas Vaeth: >
    Thomas Vaeth was born in New York, raised in Pennsylvania, and transplanted in Washington. He was a Web Developer at Urban Influence, but now he's a Software Engineer at Getty Images.

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - node_modules
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
